# Generated by Django 6.0.3 on 2026-04-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_album_art_url_card_preview_url_card_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='preview_url',
        ),
    ]
