# Generated by Django 5.2.7 on 2026-01-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='set',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
