# Generated by Django 5.2.7 on 2026-01-20 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_set_alter_card_answer_alter_card_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='set',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.set'),
        ),
    ]
