# Generated by Django 5.2.7 on 2026-01-20 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_user_set_owner_set_saved_by_alter_card_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='set',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
