# Generated by Django 5.2.7 on 2026-01-20 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_set_saved_by_set_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='users',
        ),
        migrations.AddField(
            model_name='set',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
