# Generated by Django 6.0.3 on 2026-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_set_studydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='album_art_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='track_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
