# Generated by Django 5.2.7 on 2026-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_set_studydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydata',
            name='last_studied',
            field=models.DateField(blank=True, null=True),
        ),
    ]
